-- 2026-07-20: Dormant durable action idempotency and final receipt state.
-- Apply with the repository's direct SQL migration process (psql -f).

CREATE TABLE IF NOT EXISTS action_operations (
  operation_id VARCHAR(36) PRIMARY KEY DEFAULT (gen_random_uuid())::text,
  contract_version VARCHAR(64) NOT NULL,
  actor_pubkey VARCHAR(64) NOT NULL,
  oauth_client_id VARCHAR(256) NOT NULL,
  token_jti VARCHAR(128) NOT NULL,
  token_reference_sha256 VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  resource_id VARCHAR(256),
  request_sha256 VARCHAR(64) NOT NULL,
  idempotency_key_sha256 VARCHAR(64) NOT NULL,
  request_fingerprint_sha256 VARCHAR(64) NOT NULL,
  step_up_challenge_id VARCHAR(32),
  step_up_verification_sha256 VARCHAR(64),
  policy_version VARCHAR(64) NOT NULL,
  authorization_decision_sha256 VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  reserved_at TIMESTAMP WITH TIME ZONE NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  failure_code VARCHAR(64),
  result_sha256 VARCHAR(64),
  receipt_json JSONB,
  receipt_sha256 VARCHAR(64),
  receipt_signature TEXT,
  signer_public_key VARCHAR(66),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uq_action_operations_idempotency_namespace UNIQUE (actor_pubkey, oauth_client_id, idempotency_key_sha256),
  CONSTRAINT ck_action_operations_operation_id_length CHECK (length(operation_id) = 36),
  CONSTRAINT ck_action_operations_actor_pubkey_length CHECK (length(actor_pubkey) = 64),
  CONSTRAINT ck_action_operations_client_id_length CHECK (length(oauth_client_id) BETWEEN 1 AND 256),
  CONSTRAINT ck_action_operations_token_jti_length CHECK (length(token_jti) BETWEEN 1 AND 128),
  CONSTRAINT ck_action_operations_action_length CHECK (length(action) BETWEEN 1 AND 64),
  CONSTRAINT ck_action_operations_resource_id_length CHECK (resource_id IS NULL OR length(resource_id) BETWEEN 1 AND 256),
  CONSTRAINT ck_action_operations_token_reference_hash_length CHECK (length(token_reference_sha256) = 64),
  CONSTRAINT ck_action_operations_request_hash_length CHECK (length(request_sha256) = 64),
  CONSTRAINT ck_action_operations_idempotency_hash_length CHECK (length(idempotency_key_sha256) = 64),
  CONSTRAINT ck_action_operations_fingerprint_hash_length CHECK (length(request_fingerprint_sha256) = 64),
  CONSTRAINT ck_action_operations_authorization_hash_length CHECK (length(authorization_decision_sha256) = 64),
  CONSTRAINT ck_action_operations_step_up_challenge_length CHECK (step_up_challenge_id IS NULL OR length(step_up_challenge_id) = 32),
  CONSTRAINT ck_action_operations_step_up_hash_length CHECK (step_up_verification_sha256 IS NULL OR length(step_up_verification_sha256) = 64),
  CONSTRAINT ck_action_operations_result_hash_length CHECK (result_sha256 IS NULL OR length(result_sha256) = 64),
  CONSTRAINT ck_action_operations_receipt_hash_length CHECK (receipt_sha256 IS NULL OR length(receipt_sha256) = 64),
  CONSTRAINT ck_action_operations_signer_key_length CHECK (signer_public_key IS NULL OR length(signer_public_key) = 66),
  CONSTRAINT ck_action_operations_state CHECK (state IN ('reserved','executing','completed','failed','indeterminate')),
  CONSTRAINT ck_action_operations_step_up_pair CHECK ((step_up_challenge_id IS NULL) = (step_up_verification_sha256 IS NULL)),
  CONSTRAINT ck_action_operations_started_order CHECK (started_at IS NULL OR started_at >= reserved_at),
  CONSTRAINT ck_action_operations_completed_order CHECK (completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)),
  CONSTRAINT ck_action_operations_state_started_at CHECK ((state = 'reserved' AND started_at IS NULL) OR (state != 'reserved' AND started_at IS NOT NULL)),
  CONSTRAINT ck_action_operations_completed_result CHECK (state != 'completed' OR (result_sha256 IS NOT NULL AND failure_code IS NULL)),
  CONSTRAINT ck_action_operations_failed_code CHECK (state != 'failed' OR (failure_code IS NOT NULL AND length(failure_code) BETWEEN 1 AND 64 AND result_sha256 IS NULL)),
  CONSTRAINT ck_action_operations_nonterminal_no_receipt CHECK (state NOT IN ('reserved','executing','indeterminate') OR (completed_at IS NULL AND failure_code IS NULL AND result_sha256 IS NULL AND receipt_json IS NULL AND receipt_sha256 IS NULL AND receipt_signature IS NULL AND signer_public_key IS NULL)),
  CONSTRAINT ck_action_operations_terminal_receipt CHECK (state NOT IN ('completed','failed') OR (completed_at IS NOT NULL AND receipt_json IS NOT NULL AND receipt_sha256 IS NOT NULL AND receipt_signature IS NOT NULL AND signer_public_key IS NOT NULL)),
  CONSTRAINT ck_action_operations_receipt_all_or_none CHECK ((receipt_json IS NULL AND receipt_sha256 IS NULL AND receipt_signature IS NULL AND signer_public_key IS NULL) OR (receipt_json IS NOT NULL AND receipt_sha256 IS NOT NULL AND receipt_signature IS NOT NULL AND signer_public_key IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_action_operations_operation_state ON action_operations (state);
CREATE INDEX IF NOT EXISTS idx_action_operations_updated_at ON action_operations (updated_at);
